package io.github.rawchickenneg.cnmb.common.registry;

import io.github.rawchickenneg.cnmb.ClayNoMoreBalanced;
import io.github.rawchickenneg.cnmb.common.item.*;
import io.github.rawchickenneg.cnmb.common.item.clayballs.*;
import io.github.rawchickenneg.cnmb.common.item.throwableitems.*;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.*;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class ItemRegistry {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, ClayNoMoreBalanced.MOD_ID);
    public static final RegistryObject<Item> clayIngot = ITEMS.register("clay_ingot", () -> new SimpleFoiledItem(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.RARE)));
    public static final RegistryObject<Item> clayNugget = ITEMS.register("clay_nugget", () -> new SimpleFoiledItem (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.RARE)));
    public static final RegistryObject<Item> clayScrap = ITEMS.register("clay_scrap", () -> new SimpleFoiledItem (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.RARE)));
    public static final RegistryObject<Item> clayShard = ITEMS.register("clay_shard", () -> new SimpleFoiledItem (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.RARE)));
    public static final RegistryObject<Item> clayVug = ITEMS.register("clay_vug", () -> new SimpleFoiledItem (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.RARE)));
    public static final RegistryObject<Item> clayPearl = ITEMS.register("clay_pearl", () -> new SimpleFoiledItem (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.RARE)));
    public static final RegistryObject<Item> clayGem = ITEMS.register("clay_gem", () -> new SimpleFoiledItem (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.RARE)));
    public static final RegistryObject<Item> clayStar = ITEMS.register("clay_star", () -> new SimpleFoiledItem (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> theUltimateGalaclay = ITEMS.register("the_ultimate_galaclay", () -> new SimpleFoiledItem (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> clayNoMoreBalanced = ITEMS.register("clay_no_more_balanced", () -> new SimpleFoiledItem (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> infiniteClayCatalyst = ITEMS.register("infinite_clay_catalyst", () -> new SimpleFoiledItem (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> clayRing = ITEMS.register("clay_ring", () -> new ClayRing(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).stacksTo(1)));
    public static final RegistryObject<Item> clayTotem = ITEMS.register("clay_totem", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> clayTrident = ITEMS.register("clay_trident", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> clayElytra = ITEMS.register("clay_elytra", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).craftRemainder(Items.ELYTRA).stacksTo(1)));
    public static final RegistryObject<Item> clayRod = ITEMS.register("clay_rod", () -> new SimpleFoiledItem(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.RARE)));
    public static final RegistryObject<Item> claymore = ITEMS.register("claymore", () -> new Claymore(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.EPIC).stacksTo(1)));
    public static final RegistryObject<Item> clayBowItem = ITEMS.register("clay_bow", () -> new ClayBowItem(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.RARE).stacksTo(1)));
    public static final RegistryObject<Item> axolotlClayBallBlue = ITEMS.register("axolotl_clay_ball_blue", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.RARE)));
    public static final RegistryObject<Item> axolotlClayBallCyan = ITEMS.register("axolotl_clay_ball_cyan", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> axolotlClayBallLucy = ITEMS.register("axolotl_clay_ball_lucy", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> axolotlClayBallGold = ITEMS.register("axolotl_clay_ball_gold", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> axolotlClayBallWild = ITEMS.register("axolotl_clay_ball_wild", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> tinyVexClayBall = ITEMS.register("tiny_vex_clay_ball", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> batClayBall = ITEMS.register("bat_clay_ball", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> ravagerMetalParts = ITEMS.register("ravager_metal_parts", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> dryClayBall = ITEMS.register("dry_clay_ball", () -> new DryClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> flowerClayBall = ITEMS.register("flower_clay_ball", () -> new FlowerClayBall (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> gildedClayBall = ITEMS.register("gilded_clay_ball", () -> new GildedClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> honeyClayBall = ITEMS.register("honey_clay_ball", () -> new BeehiveClayBallItem(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> leavesClayBall = ITEMS.register("leaves_clay_ball", () -> new LeavesClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> spongeClayBall = ITEMS.register("sponge_clay_ball", () -> new SpongeClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> stickyClayBall = ITEMS.register("sticky_clay_ball", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> stoneClayBall = ITEMS.register("stone_clay_ball", () -> new StoneClayBall (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> lazuliClayBall = ITEMS.register("lazuli_clay_ball", () -> new LazuliClayBall (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> glowstoneClayBall = ITEMS.register("glowstone_clay_ball", () -> new GlowstoneClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> baseClayBall = ITEMS.register("base_clay_ball", () -> new BaseClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));

    public static final RegistryObject<Item> snowClayBall = ITEMS.register("snow_clay_ball", () -> new SnowClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> eggClayBall = ITEMS.register("egg_clay_ball", () -> new EggClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> enderClayBall = ITEMS.register("ender_clay_ball", () -> new EnderClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> exchangeClayBall = ITEMS.register("exchange_clay_ball", () -> new ExchangeClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> burnClayBall = ITEMS.register("burn_clay_ball", () -> new BurnClayBallItem(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> TNTClayBall = ITEMS.register("tnt_clay_ball", () -> new TNTClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> explodeClayBall = ITEMS.register("explode_clay_ball", () -> new ExplodeClayBallItem(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> advancedExplodeClayBall = ITEMS.register("advanced_explode_clay_ball", () -> new AdvancedExplodeClayBallItem(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> ultimateExplodeClayBall = ITEMS.register("ultimate_explode_clay_ball", () -> new UltimateExplodeClayBallItem(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> phantomClayBall = ITEMS.register("phantom_clay_ball", () -> new PhantomClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> recallClayBall = ITEMS.register("recall_clay_ball", () -> new RecallClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> vexClayBall = ITEMS.register("vex_clay_ball", () -> new VexClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> voidClayBall = ITEMS.register("void_clay_ball", () -> new VoidClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> chorusClayBall = ITEMS.register("chorus_clay_ball", () -> new ChorusClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> lightingClayBall = ITEMS.register("lighting_clay_ball", () -> new LightingClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> basketClayBall = ITEMS.register("basket_clay_ball", () -> new BasketClayBallItem(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> pullClayBall = ITEMS.register("pull_clay_ball", () -> new PullClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> flintClayBall = ITEMS.register("flint_clay_ball", () -> new FlintClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> quartzClayBall = ITEMS.register("quartz_clay_ball", () -> new QuartzClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> obsidianClayBall = ITEMS.register("obsidian_clay_ball", () -> new ObsidianClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> goldenClayBall = ITEMS.register("golden_clay_ball", () -> new GoldenClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> amethystClayBall = ITEMS.register("amethyst_clay_ball", () -> new AmethystClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> glowClayBall = ITEMS.register("glow_clay_ball", () -> new GlowClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> boneClayBall = ITEMS.register("bone_clay_ball", () -> new BoneClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> ravagerClayBall = ITEMS.register("ravager_clay_ball", () -> new RavagerClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> pillagerClayBall = ITEMS.register("pillager_clay_ball", () -> new PillagerClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> prismarineClayBall = ITEMS.register("prismarine_clay_ball", () -> new PrismarineClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> duplicateClayBall = ITEMS.register("duplicate_clay_ball", () -> new DuplicateClayBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> throwableClayBall = ITEMS.register("throwable_clay_ball", () -> new ThrowableClayBallItem(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> throwableBrick = ITEMS.register("throwable_brick", () -> new ThrowableBrickItem(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> throwableArrow = ITEMS.register("throwable_arrow", () -> new ThrowableArrowItem(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> throwableFireCharge = ITEMS.register("throwable_fire_charge", () -> new ThrowableFireChargeItem(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> throwableIronIngot = ITEMS.register("throwable_iron_ingot", () -> new ThrowableIronIngotItem(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> throwableGoldIngot = ITEMS.register("throwable_gold_ingot", () -> new ThrowableGoldIngotItem(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> throwableNetheriteIngot = ITEMS.register("throwable_netherite_ingot", () -> new ThrowableNetheriteIngotItem(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> throwableTorch = ITEMS.register("throwable_torch", () -> new ThrowableTorchItem(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));

    public static final RegistryObject<Item> clayBlock = ITEMS.register("clay_block", () -> new ItemNameBlockItem(BlockRegistry.CLAY_BLOCK.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> clayTreeSapling = ITEMS.register("clay_tree_sapling", () -> new ItemNameBlockItem(BlockRegistry.CLAY_TREE_SAPLING.get(), new Item.Properties().rarity(Rarity.UNCOMMON).tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> clayRollBlock = ITEMS.register("clay_roll_block", () -> new ItemNameBlockItem(BlockRegistry.CLAY_ROLL_BLOCK.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> naturalSclameBlock = ITEMS.register("natural_sclame_block", () -> new ItemNameBlockItem(BlockRegistry.NATURAL_SCLAME_BLOCK.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> clayLog = ITEMS.register("clay_log", () -> new ItemNameBlockItem(BlockRegistry.CLAY_LOG.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> amethystShowcase = ITEMS.register("amethyst_showcase", () -> new ItemNameBlockItem(BlockRegistry.AMETHYST_SHOWCASE.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> enderPearlBlock = ITEMS.register("ender_pearl_block", () -> new ItemNameBlockItem(BlockRegistry.ENDER_PEARL_BLOCK.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> porcelainBlock = ITEMS.register("porcelain_block", () -> new ItemNameBlockItem(BlockRegistry.PORCELAIN_BLOCK.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> porcelainTile = ITEMS.register("porcelain_tile", () -> new ItemNameBlockItem(BlockRegistry.PORCELAIN_TILE.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> porcelainTileLarge = ITEMS.register("porcelain_tile_large", () -> new ItemNameBlockItem(BlockRegistry.PORCELAIN_TILE_LARGE.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> porcelainTileTiny = ITEMS.register("porcelain_tile_tiny", () -> new ItemNameBlockItem(BlockRegistry.PORCELAIN_TILE_TINY.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> toilet = ITEMS.register("toilet", () -> new ItemNameBlockItem(BlockRegistry.TOILET.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> netheriteSponge = ITEMS.register("netherite_sponge", () -> new ItemNameBlockItem(BlockRegistry.NETHERITE_SPONGE_BLOCK.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).fireResistant()));
    public static final RegistryObject<Item> netheriteSpongeAbsorbed = ITEMS.register("netherite_sponge_absorbed", () -> new ItemNameBlockItem(BlockRegistry.NETHERITE_SPONGE_ABSORBED_BLOCK.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).craftRemainder(ItemRegistry.netheriteSponge.get()).stacksTo(1).fireResistant()));
    public static final RegistryObject<Item> sclameBall = ITEMS.register("sclame_ball", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).food((new FoodProperties.Builder()).nutrition(6).saturationMod(0.5f).build())));

    public static final RegistryObject<Item> sclamePotato = ITEMS.register("sclame_potato", () -> new ItemNameBlockItem(BlockRegistry.SCLAME_POTATO_BLOCK.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).food((new FoodProperties.Builder()).nutrition(5).saturationMod(1f).build())));
    public static final RegistryObject<Item> sproutingSclamePotato = ITEMS.register("sprouting_sclame_potato", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> sclameMeat = ITEMS.register("sclame_meat", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).food((new FoodProperties.Builder()).nutrition(12).saturationMod(1.4f).build())));
    public static final RegistryObject<Item> brickedPotato = ITEMS.register("bricked_potato", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).food((new FoodProperties.Builder()).nutrition(12).saturationMod(0.8f).effect(new MobEffectInstance(MobEffects.HUNGER, 600, 1), 1.0F).effect(new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 600, 1), 1.0F).effect(new MobEffectInstance(MobEffects.MOVEMENT_SLOWDOWN, 600, 0), 1.0F).build())));
    public static final RegistryObject<Item> sclameApple = ITEMS.register("sclame_apple", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).food((new FoodProperties.Builder()).nutrition(8).saturationMod(1.2f).build())));
    public static final RegistryObject<Item> sclameBread = ITEMS.register("sclame_bread", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).food((new FoodProperties.Builder()).nutrition(10).saturationMod(1.1f).build())));
    public static final RegistryObject<Item> sclamePie = ITEMS.register("sclame_pie", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).food((new FoodProperties.Builder()).nutrition(16).saturationMod(1.25f).build())));
    public static final RegistryObject<Item> sclameCake = ITEMS.register("sclame_cake", () -> new ItemNameBlockItem(BlockRegistry.SCLAME_CAKE_BLOCK.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> clayCream = ITEMS.register("clay_cream", () -> new ClayCream(new Item.Properties().stacksTo(1).tab(ClayNoMoreBalanced.CREATIVE_TAB).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> clayCreamBall = ITEMS.register("clay_cream_ball", () -> new ClayCreamBall(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> terracottaDust = ITEMS.register("terracotta_dust", () -> new Item(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> netherBrickDust = ITEMS.register("nether_brick_dust", () -> new Item(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> porcelainBrick = ITEMS.register("porcelain_brick", () -> new Item(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> porcelainHelmet = ITEMS.register("porcelain_helmet", () -> new ArmorItem(ArmorTier.PORCELAIN, EquipmentSlot.HEAD, (new Item.Properties()).tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> porcelainChestplate = ITEMS.register("porcelain_chestplate", () -> new ArmorItem(ArmorTier.PORCELAIN, EquipmentSlot.CHEST, (new Item.Properties()).tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> porcelainLeggings = ITEMS.register("porcelain_leggings", () -> new ArmorItem(ArmorTier.PORCELAIN, EquipmentSlot.LEGS, (new Item.Properties()).tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> porcelainBoots = ITEMS.register("porcelain_boots", () -> new ArmorItem(ArmorTier.PORCELAIN, EquipmentSlot.FEET, (new Item.Properties()).tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> porcelainHoe = ITEMS.register("porcelain_hoe", () -> new HoeItem(ItemTier.Porcelain, -2, -1.0F, (new Item.Properties()).tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> porcelainAxe = ITEMS.register("porcelain_axe", () -> new AxeItem(ItemTier.Porcelain, 6.0F, -3.1F, (new Item.Properties()).tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> porcelainPickaxe = ITEMS.register("porcelain_pickaxe", () -> new PickaxeItem(ItemTier.Porcelain, 1, -2.8F, (new Item.Properties()).tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> porcelainSword = ITEMS.register("porcelain_sword", () -> new SwordItem(ItemTier.Porcelain, 3, -2.4F, (new Item.Properties()).tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> porcelainShovel = ITEMS.register("porcelain_shovel", () -> new ShovelItem(ItemTier.Porcelain, 1.5F, -1F, (new Item.Properties()).tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> ruby = ITEMS.register("ruby", () -> new Item(new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> tinyBasePowder = ITEMS.register("tiny_base_powder", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> basePowder = ITEMS.register("base_powder", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> chickenChop = ITEMS.register("chicken_chop", () -> new Item (new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB).food((new FoodProperties.Builder()).nutrition(10).saturationMod(1.2f).alwaysEat().effect(new MobEffectInstance(MobEffects.REGENERATION, 2400, 1), 1.0F).effect(new MobEffectInstance(MobEffects.MOVEMENT_SPEED, 2400, 0), 1.0F).build())));
    public static final RegistryObject<Item> buddingRoseQuartz = ITEMS.register("budding_rose_quartz", () -> new ItemNameBlockItem(BlockRegistry.BUDDING_ROSE_QUARTZ.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> SmallRoseQuartzBud = ITEMS.register("small_rose_quartz_bud", () -> new ItemNameBlockItem(BlockRegistry.SMALL_ROSE_QUARTZ_BUD.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> MediumRoseQuartzBud = ITEMS.register("medium_rose_quartz_bud", () -> new ItemNameBlockItem(BlockRegistry.MEDIUM_ROSE_QUARTZ_BUD.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> LargeRoseQuartzBud = ITEMS.register("large_rose_quartz_bud", () -> new ItemNameBlockItem(BlockRegistry.LARGE_ROSE_QUARTZ_BUD.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));
    public static final RegistryObject<Item> RoseQuartzCluster = ITEMS.register("rose_quartz_cluster", () -> new ItemNameBlockItem(BlockRegistry.ROSE_QUARTZ_CLUSTER.get(), new Item.Properties().tab(ClayNoMoreBalanced.CREATIVE_TAB)));

}